### ISSUE TITLE
Porting the library to Windows

### ISSUE THREAD

**Issue by ankitp94** [temken/comparxiv#10]
Hi Timon,

Great library! I tried using it on Windows Powershell but some commands fail because they are Linux specific, for example, "rm", "mv" and path formats.

Using python libraries to interact with file system would resolve these issues.

**Comment by temken** [comment]
Hi ankitp94,

That is a great idea, I haven't even thought about Windows.

I can look into it. The terminal commands would have to be made os-specific everywhere, and ideally, I would like to run corresponding tests on travis.

Since I haven't used Windows in more than a decade, is there anything else I should be aware of? Is there a package manager for windows, which you can use to install a tex distribution from the terminal?

Best,
Timon

**Comment by ankitp94** [comment]
Hi Timon,
I don't think there is a command line argument for installing tex on Windows but once installed, it is available via command line. The tex commands are the same (latexdiff and pdflatex). 
The only thing to look out for is that while passing paths as arguments to tex, remember to use os.path. If you can make it os-independent and only assume the existence of latexdiff and pdflatex, that would be reallly helpful.

Thanks,
Ankit

**Comment by temken** [comment]
Hi Ankit,

Thanks for your reply. I just pushed a few changes to the [dev](https://github.com/temken/comparxiv/tree/dev) branch. The main changes are in [47f5462](https://github.com/temken/comparxiv/commit/47f5462dac3ebd94b27932a98deccaf7f42677bc).

All the paths should be os-independent now. I'm a bit worried about this line, where the source files are unpacked:

`os.system('tar -xzf '+path_source +' -C '+ path_destination)`

I'm not sure if this works on windows, and unfortunately I don't have access to a windows machine. Could you give it a try?

Best,
Timon

**Comment by ankitp94** [comment]
Hi Timon,

I just checked it on my Windows machine and it is working perfectly :) 
Thanks again for such a quick response.

Thanks,
Ankit

**Comment by temken** [comment]
Hi Ankit,

That's great. Then I'll proceed to update the version on PyPI.

Thanks again for the suggestion.
Best,
Timon
