### ISSUE TITLE
What should I add "comparxiv" to "vim ~/.zshrc"

### ISSUE THREAD

**Issue by SuperBruceJia** [temken/comparxiv#12]
Hi,
After I install comparxiv, it has not added to the path.

The error is "zsh: command not found: comparxiv".

How to add it to the path? Thanks in advance!

**Comment by temken** [comment]
I this still a problem? The command should be available after installation "out of the box".

**Comment by SuperBruceJia** [comment]
Thanks, dude! I have met another problem. 
“sh: pdflatex: command not found"
It seems that there is no pdflatex even though I have installed the texlive. 
Is there any way to solve the problem? 
Thanks in advance.

**Comment by SuperBruceJia** [comment]
Thanks, dude. It's working now!

**Comment by temken** [comment]
Perfect!
